services:
  postgres:
    container_name: e2e-test-container
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: patrol
      POSTGRES_DB: patrol
      POSTGRES_USER: patrol
      PGPASSWORD: patrol
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: ["CMD", "psql", "-h", "localhost", "-U", "patrol", "-d", "patrol"]
      interval: 5s
      timeout: 5s
      retries: 20
  payment:
    container_name: payment
    depends_on:
      postgres:
        condition: service_healthy
    build: ../../payment/
    environment:
      APPLICATION_PORT: 8081
      ENV: development
      DATA_SOURCE_URL: postgres://patrol:patrol@postgres:5432/patrol?sslmode=disable&TimeZone=Asia/Shanghai

  order:
    container_name: order
    depends_on:
      postgres:
        condition: service_healthy
    build: ../../order/
    ports:
      - "8080:8080"
    environment:
      PAYMENT_SERVICE_URL: payment:8081
      APPLICATION_PORT: 8080
      ENV: development
      DATA_SOURCE_URL: postgres://patrol:patrol@postgres:5432/patrol?sslmode=disable&TimeZone=Asia/Shanghai
